### ISSUE TITLE
Requesting Relicense to BSL

### ISSUE THREAD

**Issue by coder3101** [ZedThree/clang-tidy-review#1]
Hi Peter,
Your script to post review comments from `clang-tidy` output is very useful, however due to some limitations, I could not use your Action directly. I have created and modified your review script to meet my needs ([script here](https://github.com/BoostGSoC20/ublas/blob/github-actions/.ci/clang-tidy-review.py)) but my organization demands every code to be under Boost Software License (BSL). 

@ZedThree Could you Relicense or permit me to Relicense your script to BSL? BSL is compatible with MIT and 95% same as MIT. You can check the Boost Software License [here](https://spdx.org/licenses/BSL-1.0.html)

**Comment by coder3101** [comment]
No actions required!

**Comment by ZedThree** [comment]
Hi Ashar, I'm glad you found it useful! You may use this under BSL.
