### ISSUE TITLE
PR login name for `google-readability-todo`

### ISSUE THREAD

**Issue by bwrsandman** [ZedThree/clang-tidy-review#102]
It would be useful if the PR author's username was used for the suggested fix of `google-readability-todo`.
Currently it has `unknown`.
![image](https://github.com/ZedThree/clang-tidy-review/assets/1013356/51749df4-71e6-4544-89c9-de6993807ef3)

Clang-tidy gets the name from the `USER` environment variable, the config parameter and the config files.
This is how I would do it if it wasn't in a container.
```USER: ${{ github.event.pull_request.user.login }}```

**Comment by ZedThree** [comment]
Should be possible to pass that in as an argument?

**Comment by bwrsandman** [comment]
Should be able to do this with the github api and setting the docker's env without needing an argument.

I don't see why we'd want an argument for this unless users prefer using something else than `login`
