### ISSUE TITLE
Running commands inside the docker

### ISSUE THREAD

**Issue by umutoztunc** [ZedThree/clang-tidy-review#22]
It would be nice if we could pass some commands to docker instance apart from apt packages.

Currently, we don't keep a compilation database in our repository. We generate it during github workflows via cmake. Is there a way to make it work with this action so that we can install cmake and generate the compilation database there?

**Comment by ZedThree** [comment]
The way I do it is to have a step in the workflow that creates the compilation database first, but given that you often need to install packages in both the parent workflow and then also inside the docker container, it probably makes more sense to also pass in the CMake arguments.

**Comment by umutoztunc** [comment]
Thanks, I confirm that it works when we create the compilation database first. I am not sure whether you'd like to keep this issue open or not. Thus, I will leave it up to you.
