### ISSUE TITLE
0.8.0 doesn't work

### ISSUE THREAD

**Issue by vadi2** [ZedThree/clang-tidy-review#27]
Really excited to try the new fixits feature, but having some difficulty with the new version of the action: [build log](https://github.com/Mudlet/Mudlet/runs/5123098232?check_suite_focus=true) & [PR](https://github.com/Mudlet/Mudlet/pull/5962/files)

**Comment by ZedThree** [comment]
Thanks for the bug report! It looks like `--export-fixes` doesn't create a file if there are no suggestions. When testing, it seems I hadn't considered the case when there's nothing to report.

Should be a pretty easy fix

**Comment by ZedThree** [comment]
@vadi2 Does #28 work for you?

I really need to work out how to get CI working for this!

**Comment by vadi2** [comment]
The action worked well - https://github.com/Mudlet/Mudlet/runs/5124404130?check_suite_focus=true

clang-tidy isn't picking up a couple of fixits that it should be - digging into that, but that is a separate problem. Thanks for the quick fix!

**Comment by ZedThree** [comment]
Thanks! 0.8.1 now released
