### ISSUE TITLE
Comments doubled up

### ISSUE THREAD

**Issue by vadi2** [ZedThree/clang-tidy-review#35]
Comments from the bot are starting to come through multiple times:

![Screenshot_20220413-110935_Firefox Beta](https://user-images.githubusercontent.com/110988/163142255-2656180b-5344-4ba9-b262-95c7f9337ab8.png)

https://github.com/Mudlet/Mudlet/pull/6056#issuecomment-1097684740

**Comment by ZedThree** [comment]
Oh dear, that's not supposed to happen!
Unfortunately I won't have chance to look at this for at least a couple of
weeks, but if you figure it out, I can probably review a PR

**Comment by ZedThree** [comment]
I guess #47 sorted this one way or another
