### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by vadi2** [ZedThree/clang-tidy-review#36]
See https://github.com/Mudlet/Mudlet/runs/6125396129?check_suite_focus=true - the docker build has started to fail for some reason.

**Comment by ZedThree** [comment]
Oops, we're using `ubuntu:latest` which is now `22.04` and has different clang-tidy packages: https://packages.ubuntu.com/search?keywords=clang-tidy&searchon=names&suite=jammy&section=all

Trivial fix, although it would change the versions of clang-tidy

**Comment by jellespijker** [comment]
This still fails, even when specifying ubuntu-20.04
https://github.com/Ultimaker/CuraEngine/pull/1652

**Comment by ZedThree** [comment]
`clang-tidy-review` uses its own docker container, which is unrelated to the parent Action's container: https://github.com/Ultimaker/CuraEngine/runs/6175255484?check_suite_focus=true#step:2:5

I'll pin to ubuntu-20.04 for now.

**Comment by jellespijker** [comment]
thank you for the quick response and fix
