### ISSUE TITLE
Update to jammy (22.04 LTS)

### ISSUE THREAD

**Issue by bwrsandman** [ZedThree/clang-tidy-review#44]
Would it be possible to update to jammy which would bring support for clang-tidy up to version 14.
Using clang-tidy-14 is useful because you can now use `NOLINTBEGIN`/`NOLINTEND`

**Comment by FlorianReimold** [comment]
I made a branch some time ago where I upgraded to Ubuntu 22. I personally don't use it, as it didn't solve the issue I was dealing with.

https://github.com/FlorianReimold/clang-tidy-review/tree/feature/clang-tidy-14

@ZedThree: If you want I can make a PR

**Comment by Nerixyz** [comment]
It would be great if this action could be updated to Ubuntu 22.04 and clang-tidy-14. A lot of wrong suggestions we're having in chatterino2 while testing #50 are resolved by newer versions of clang-tidy.
