### ISSUE TITLE
How does the `exclude` parameter work?

### ISSUE THREAD

**Issue by FlorianReimold** [ZedThree/clang-tidy-review#56]
I have the following line in my GH Action:

```yaml
exclude: "/thirdparty/*,/_build/*,convert_utf.cpp,convert_utf.h,/testing/*"
```
https://github.com/eclipse-ecal/ecal/blob/8725500f16f3b70fa3f084d5d98a71b3cfaf6fae/.github/workflows/clang-tidy-review.yml#L35

The last list item is supposed to exclude all files and all subfolders from the `/testing/` folder. It however does not work and still scans files from `testing`. Any suggestions on what I did wrong?

**Comment by ZedThree** [comment]
`exclude` is handled using [`fnmatch`](https://docs.python.org/3/library/fnmatch.html):

```py
    for pattern in exclude:
        files = [f for f in files if not fnmatch.fnmatch(f, pattern)]
```

where `files` is a list of relative paths of changed files in the PR. So you should just have to drop the leading `/`

**Comment by FlorianReimold** [comment]
Ah, thanks, I changed it accordingly!
