### ISSUE TITLE
Option "apt_packages" can't find packages

### ISSUE THREAD

**Issue by marcluque** [ZedThree/clang-tidy-review#57]
We have started to use this action in our pipeline (see [here](https://github.com/Benzammour/yobemag/blob/main/.github/workflows/clang-tidy-review.yml) for the YAML file). Unfortunately, it is not installing our desired packages, which can be seen [here](https://github.com/Benzammour/yobemag/actions/runs/3314545207/jobs/5473970022#step:4:19) in an action log.

I was wondering why this is the case and I'm speculating that an `apt update` could be missing. As far as I can tell, the action is not doing that as of now. With regards to the installation of the packages I looked at [these lines](https://github.com/ZedThree/clang-tidy-review/blob/ffaff5ed1842252e556bd65365419bded8a1dd36/review.py#L182) in `review.py`.

We'd appreciate any help, thank you in advance for your time!

**Comment by FlorianReimold** [comment]
I think your quick solution would be to remove the space in between your packages:

```yaml
apt_packages: libsdl2-dev,libcriterion-dev
```

At least it works [in our gh action](https://github.com/eclipse-ecal/ecal/blob/5345a5c0a111b23f3150a28834ccb57f55924490/.github/workflows/clang-tidy-review.yml#L33) that way.

It's still a reasonable assumption that it should work like that in my opinion, so maybe someone should add a `strip()` call before passing the list as arguments.

**Comment by marcluque** [comment]
Ouh interesting, very good catch, thank you!

Unfortunately, the result remains the same (see [here](https://github.com/Benzammour/yobemag/actions/runs/3319501429/jobs/5484734402#step:4:19))

**Comment by marcluque** [comment]
> At least it works [in our gh action](https://github.com/eclipse-ecal/ecal/blob/5345a5c0a111b23f3150a28834ccb57f55924490/.github/workflows/clang-tidy-review.yml#L33) that way.

I'm not sure if this is related, but maybe using Ubuntu 20.04 vs 22.04 makes a difference here. That's something I noticed when looking at your Dockerfile.

When, for example, asking for `ninja-build` as a package, I'm getting this:
![image](https://user-images.githubusercontent.com/33261455/197736576-66262c7c-0753-456c-9b0f-6d1b669257e8.png)
[Full log](https://github.com/Benzammour/yobemag/actions/runs/3319635483/jobs/5485036270)

**Comment by FlorianReimold** [comment]
Hm, yea, we are still using the old Ubuntu 20 based docker image... 
The package is available on Ubuntu 22.04 though, I tried in a VM i have available locally. But that VM runs a Desktop version of Ubuntu 22.04.

**Comment by marcluque** [comment]
Indeed, I checked the package list too, thank you for trying the VM!
I just created a fork and added `apt-get update` before the install command and now it works 🎉

So a possible fix would actually be to update the package sources beforehand 🤔

**Comment by marcluque** [comment]
> Updating the packages seems like a good idea! Please could you make a PR @marcluque ?

Glady! I've opened a PR.

**Comment by ZedThree** [comment]
Closed in #58
