### ISSUE TITLE
Hardcoded GitHub API url doesn't work on GitHub Enterprise Server

### ISSUE THREAD

**Issue by rajbos** [ZedThree/clang-tidy-review#64]
The hardcoded GitHub API url doesn't work on GitHub Enterprise Server, the environment variable `GITHUB_API_URL` should be used.

Code reference:
https://github.com/ZedThree/clang-tidy-review/blob/master/post/clang_tidy_review/__init__.py#L115

**Comment by ZedThree** [comment]
Ah, good point! PRs welcome :)

**Comment by rajbos** [comment]
I've tried to address it, hope that works (no Python expert here 🤗).
