### ISSUE TITLE
0.12.0 fails to build

### ISSUE THREAD

**Issue by vadi2** [ZedThree/clang-tidy-review#72]
Excited to try the new version with support for a split workflow, but it doesn't seem to be building: https://github.com/Mudlet/Mudlet/actions/runs/4502862552/jobs/7925284185?pr=6689#step:2:909

**Comment by ZedThree** [comment]
I've just released v0.12.1 that (hopefully!) fixes this

**Comment by vadi2** [comment]
Thanks, the action does build now!
