### ISSUE TITLE
Feedback posted as comments instead of annotations

### ISSUE THREAD

**Issue by vadi2** [ZedThree/clang-tidy-review#77]
I [enabled annotations](https://github.com/Mudlet/Mudlet/actions/runs/4533629180/jobs/7986697572#step:13:8) in my config, but all the feedback still got posted [as comments](https://github.com/Mudlet/Mudlet/pull/6698#pullrequestreview-1359321189). What could be going wrong?

**Comment by ZedThree** [comment]
Oh, if you're using `split_workflow`, that needs to be on the `post` action, rather than `review`. Sorry, that's not very clear in the docs

**Comment by vadi2** [comment]
Aha, thanks. What about `lgtm_comment_body`?
