### ISSUE TITLE
Add option to let clang-tidy find the config file on its own

### ISSUE THREAD

**Issue by psalz** [ZedThree/clang-tidy-review#80]
By default clang-tidy will attempt to find the `.clang-tidy` file that is closest to the source file it is currently checking. This is useful if one wants to have different sets of checks for different folders. By setting `--config-file` explicitly this behavior is overriden, and all files are checked with the same config. It would be great if there was an option to disable the Python wrapper from passing the option at all!

**Comment by ZedThree** [comment]
Ah, I didn't realise that was possible! Ok, we need to a bit more clever about setting that option then

**Comment by ZedThree** [comment]
PR in #96 that fixes this
