### ISSUE TITLE
Option to not use line filters

### ISSUE THREAD

**Issue by bwrsandman** [ZedThree/clang-tidy-review#99]
I'm looking for a way to create an action that only triggers if a `.clang-tidy` file has been changed.
This would presumably have an empty line filter. However, practically this would require running clang tidy on the whole project since that project could be non compliant.
Is there a way to not issue a line filter?

**Comment by ZedThree** [comment]
I think in that case, it's probably best to run `clang-tidy` manually

**Comment by bwrsandman** [comment]
What about running nightlies that check the whole project?
Sometimes having line filters results in old code having old rules.
Seems like this action is well positioned to avoid doing this manually?

**Comment by ZedThree** [comment]
Hmm, that would be useful, yeah. I guess you could turn off posting comments and just have it upload the review as an artefact so that it works on plain commits and not just PRs.

**Comment by bwrsandman** [comment]
Closing because it's easy to just make a workflow that calls clang tody
